/** Qualified element → the command id that creates or edits it (see ../ledger.ts). */
export default {
  // Design ▸ Themes / Colors / Fonts / Effects (the theme part, DrawingML).
  "a:theme": "design.theme",
  "a:themeElements": "design.theme",
  "a:objectDefaults": "design.theme",
  "a:extraClrSchemeLst": "design.theme",
  "a:clrScheme": "design.colors",
  "a:dk1": "design.colors",
  "a:lt1": "design.colors",
  "a:dk2": "design.colors",
  "a:lt2": "design.colors",
  "a:accent1": "design.colors",
  "a:accent2": "design.colors",
  "a:accent3": "design.colors",
  "a:accent4": "design.colors",
  "a:accent5": "design.colors",
  "a:accent6": "design.colors",
  "a:hlink": "design.colors",
  "a:folHlink": "design.colors",
  "a:fontScheme": "design.fonts",
  "a:majorFont": "design.fonts",
  "a:minorFont": "design.fonts",
  "a:fmtScheme": "design.effects",
  "a:fillStyleLst": "design.effects",
  "a:lnStyleLst": "design.effects",
  "a:effectStyleLst": "design.effects",
  "a:effectStyle": "design.effects",
  "a:bgFillStyleLst": "design.effects",
  // Design ▸ Paragraph Spacing / Document Formatting.
  "w:docDefaults": "design.styleSet",
  "w:pPrDefault": "design.paragraphSpacing",
  // Design ▸ Page Background.
  "w:background": "design.pageColor",
  "w:displayBackgroundShape": "design.pageColor",
  "v:background": "design.pageColor",
  "v:textpath": "design.watermark",
  "v:shapetype": "design.watermark",
  "w:pgBorders": "design.pageBorders",
  // Layout.
  "w:cols": "layout.columns",
  "w:col": "layout.columns",
  "w:lnNumType": "layout.lineNumbers",
  "w:suppressLineNumbers": "layout.suppressLineNumbers",
  "w:docGrid": "layout.pageSetup",
  "w:type": "section.break",
  "w:mirrorMargins": "layout.pageSetup",
  "w:gutterAtTop": "layout.pageSetup",
  "w:printTwoOnOne": "layout.pageSetup",
  "w:bookFoldPrinting": "layout.pageSetup",
  "w:bookFoldPrintingSheets": "layout.pageSetup",
  "w:evenAndOddHeaders": "layout.pageSetup",
  "w:autoHyphenation": "layout.hyphenation",
  "w:hyphenationZone": "layout.hyphenation",
  "w:consecutiveHyphenLimit": "layout.hyphenation",
  "w:doNotHyphenateCaps": "layout.hyphenation",
} satisfies Record<string, string>;
