/** Qualified element → the command id that creates or edits it (see ../ledger.ts). */

// Every OMML structure the linear-format equation builder writes.
const EQUATION = "insert.equation";
const MATH_ELEMENTS = [
  "m:oMath",
  "m:oMathPara",
  "m:r",
  "m:t",
  "m:rPr",
  "m:nor",
  "m:sty",
  "m:f",
  "m:fPr",
  "m:type",
  "m:num",
  "m:den",
  "m:sSup",
  "m:sSub",
  "m:sSubSup",
  "m:sup",
  "m:sub",
  "m:e",
  "m:rad",
  "m:radPr",
  "m:degHide",
  "m:deg",
  "m:nary",
  "m:naryPr",
  "m:chr",
  "m:limLoc",
  "m:subHide",
  "m:supHide",
  "m:d",
  "m:dPr",
  "m:begChr",
  "m:sepChr",
  "m:endChr",
  "m:func",
  "m:fName",
  "m:acc",
  "m:accPr",
  "m:bar",
  "m:barPr",
  "m:pos",
  "m:limLow",
  "m:limUpp",
  "m:lim",
  "m:m",
  "m:mr",
  "m:eqArr",
  "m:borderBox",
] as const;

// Legacy form fields (Insert ▸ Field ▸ FORMTEXT / FORMCHECKBOX / FORMDROPDOWN).
const FORM_FIELD = "insert.formField";
const FORM_FIELD_ELEMENTS = [
  "w:ffData",
  "w:name",
  "w:enabled",
  "w:calcOnExit",
  "w:helpText",
  "w:textInput",
  "w:default",
  "w:maxLength",
  "w:checkBox",
  "w:sizeAuto",
  "w:size",
  "w:ddList",
  "w:listEntry",
] as const;

export default {
  ...Object.fromEntries(MATH_ELEMENTS.map((e) => [e, EQUATION])),
  ...Object.fromEntries(FORM_FIELD_ELEMENTS.map((e) => [e, FORM_FIELD])),
  "w:sym": "insert.symbol",
  "w:noBreakHyphen": "insert.symbol",
  "w:softHyphen": "insert.symbol",
  "w:fldChar": "insert.field",
  "w:instrText": "insert.field",
  "w:framePr": "insert.dropCap",
  "w:pict": "insert.signatureLine",
  "v:shape": "insert.signatureLine",
  "v:shapetype": "insert.signatureLine",
  "v:imagedata": "insert.signatureLine",
  "o:signatureline": "insert.signatureLine",
  "o:lock": "insert.signatureLine",
  "w:titlePg": "insert.coverPage",
  "w:pgNumType": "headerFooter.pageNumberFormat",
  "w:headerReference": "headerFooter.headerPreset",
  "w:footerReference": "headerFooter.footerPreset",
  "w:hdr": "headerFooter.headerPreset",
  "w:ftr": "headerFooter.footerPreset",
} satisfies Record<string, string>;
