/** Qualified element → the command id that creates or edits it (see ../ledger.ts). */
export default {
  // Wrap Text, Position, Layout Options (commands/drawing.ts).
  "wp:wrapSquare": "drawing.wrap",
  "wp:wrapTight": "drawing.wrap",
  "wp:wrapThrough": "drawing.wrap",
  "wp:wrapTopAndBottom": "drawing.wrap",
  "wp:wrapNone": "drawing.wrap",
  "wp:effectExtent": "drawing.wrap",
  "wp:simplePos": "drawing.wrap",
  "wp:wrapPolygon": "drawing.anchorOptions",
  "wp:start": "drawing.anchorOptions",
  "wp:lineTo": "drawing.anchorOptions",
  "wp:positionH": "drawing.position",
  "wp:positionV": "drawing.position",
  "wp:posOffset": "drawing.position",
  "wp:align": "drawing.position",
  "wp:cNvGraphicFramePr": "drawing.aspectLock",
  "a:graphicFrameLocks": "drawing.aspectLock",
  "a:picLocks": "drawing.aspectLock",
  "pic:cNvPicPr": "drawing.aspectLock",
  "a:hlinkClick": "drawing.hyperlink",
  // Crop, Crop to Shape (commands/image.ts).
  "a:srcRect": "image.crop",
  "a:stretch": "image.insert",
  "a:fillRect": "image.insert",
  "a:prstGeom": "image.geometry",
  "a:avLst": "image.geometry",
  // Picture Border.
  "a:ln": "image.outline",
  "a:solidFill": "image.outline",
  "a:srgbClr": "image.outline",
  "a:prstDash": "image.outline",
  "a:noFill": "image.outline",
  "a:alpha": "image.effects",
  // Picture Effects.
  "a:effectLst": "image.effects",
  "a:outerShdw": "image.effects",
  "a:innerShdw": "image.effects",
  "a:glow": "image.effects",
  "a:softEdge": "image.effects",
  "a:reflection": "image.effects",
  "a:scene3d": "image.effects",
  "a:camera": "image.effects",
  "a:lightRig": "image.effects",
  "a:rot": "image.effects",
  "a:sp3d": "image.effects",
  "a:bevelT": "image.effects",
  // Corrections, Color, Transparency.
  "a:lum": "image.adjust",
  "a:grayscl": "image.adjust",
  "a:biLevel": "image.adjust",
  "a:duotone": "image.adjust",
  "a:clrChange": "image.adjust",
  "a:clrFrom": "image.adjust",
  "a:clrTo": "image.adjust",
  "a:alphaModFix": "image.adjust",
  "a:hsl": "image.adjust",
} satisfies Record<string, string>;
