/** Qualified element → the command id that creates or edits it (see ../ledger.ts). */
export default {
  "w:tblStyle": "table.setStyle",
  "w:tblLook": "table.setLook",
  "w:tblStylePr": "table.modifyStyle",
  "w:tblStyleRowBandSize": "table.setStyle",
  "w:tblStyleColBandSize": "table.setStyle",
  "w:tblW": "table.properties",
  "w:tblInd": "table.properties",
  "w:tblCellMar": "table.properties",
  "w:tblCellSpacing": "table.properties",
  "w:tblpPr": "table.properties",
  "w:tblOverlap": "table.properties",
  "w:tblCaption": "table.properties",
  "w:tblDescription": "table.properties",
  "w:tblLayout": "table.autoFit",
  "w:tcW": "table.properties",
  "w:tcMar": "table.properties",
  "w:noWrap": "table.properties",
  "w:tcFitText": "table.properties",
  "w:cantSplit": "table.properties",
  "w:gridSpan": "table.mergeCells",
  "w:vMerge": "table.mergeCells",
  "w:gridAfter": "table.deleteCells",
  "w:tcBorders": "table.rangeBorders",
  "w:tblBorders": "table.rangeBorders",
  "w:insideH": "table.rangeBorders",
  "w:insideV": "table.rangeBorders",
  "w:tl2br": "table.rangeBorders",
  "w:tr2bl": "table.rangeBorders",
  "w:tblHeader": "table.repeatHeader",
  "w:trHeight": "table.rowHeightSel",
  "w:vAlign": "table.cellAlign",
} satisfies Record<string, string>;
